version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 10
    groups:
      dotnet:
        patterns:
          - "Microsoft.*"
          - "System.*"
      surgewave:
        patterns:
          - "Kuestenlogik.Surgewave.*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    groups:
      actions:
        patterns:
          - "*"