<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);CA1003;CA2213</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\Kuestenlogik.Surgewave.Samples.DigitalTwin.Shared.csproj" />
    <PackageReference Include="Kuestenlogik.Surgewave.Client" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" />
  </ItemGroup>

</Project>
